### ISSUE TITLE
作者为什么不直接把各个平台的so包都编译好了。

### ISSUE THREAD

**Issue by z2045217** [shishuo365/libx264-android#3]
直接下载不是方便吗？我试了作者的这个。出了Relocations in generic ELF (EM: 62)问题。还有运行了build.sh没有出现libs目录。。

**Comment by shishuo365** [comment]
已经有编译好的库，位于这里 https://github.com/shishuo365/libx264-android/releases

**Comment by ibaoger** [comment]
我会在接下来的时间里处理掉这个问题，暂定版本v1.2，请关注后续项目更新。

**Comment by z2045217** [comment]
非常感谢作者。。

**Comment by ibaoger** [comment]
@z2045217 包含动态链接库的版本已经发布，v1.2
