### ISSUE TITLE
求arm64-v8a打好的包······

### ISSUE THREAD

**Issue by lzx1** [shishuo365/libx264-android#4]
对于没研究过C++的同学来说，打arm64-v8a的包简直是灾难······· 求打好的arm64-v8a的.so包······

**Comment by ibaoger** [comment]
我会在接下来的时间里处理掉这个问题，暂定版本v1.2，请关注后续项目更新。

**Comment by z2045217** [comment]
没有arm64-v8a的动态库。那个使用挺多的。

**Comment by ibaoger** [comment]
32位库要求 android API 16，
64位库要求 android API 21，
如果你的项目最低版本为21，可以考虑使用。暂定版本v1.3，马上发出来。

**Comment by ibaoger** [comment]
版本v1.3已经发布。
